### ISSUE TITLE
АА ХЕЛП

### ISSUE THREAD

**Issue by spartak110** [ratabomb/fuckclipper#1]
ебаный свет я такой додик объясни что да как. как его сделать в ехе и как конкретно его сделать. Всё понимаю, но этого я не понимаю

**Comment by ratabomb** [comment]
скачиваешь visual studio 2022 с c++ build tools, распаковываешь код, открываешь .sln файл через студию, в коде меняешь адреса на свои, в настройках проекта ставишь release и пкм-> собрать
